import numpy as np
from hep_tracking.data import generate_tracks
from hep_tracking.models import (
    knn_numpy_brute_force,
    knn_scipy_ckdtree,
    knn_sklearn_kdtree,
    knn_sklearn_balltree,
)


def test_knn_implementations_consistency():
    """Validates that all optimized kNN implementations return identical results.

    Compares the distances and indices generated by scipy and sklearn tree-based 
    algorithms against the exact numpy brute-force implementation.
    """
    features, _ = generate_tracks(n_tracks=20, hits_per_track=5, n_noise=10, seed=42)
    k_neighbors = 5

    reference_distances, reference_indices = knn_numpy_brute_force(
        features, k=k_neighbors
    )

    implementations_to_test = [
        knn_scipy_ckdtree,
        knn_sklearn_kdtree,
        knn_sklearn_balltree,
    ]

    for knn_method in implementations_to_test:
        test_distances, test_indices = knn_method(features, k=k_neighbors)

        assert np.allclose(
            reference_distances, test_distances, rtol=1e-4, atol=1e-4
        )
        assert np.array_equal(reference_indices, test_indices)