import numpy as np

from hep_tracking.config import TrackSimulationConfig
from hep_tracking.data import generate_tracks
from hep_tracking.models import NumpyBruteForce, ScipyCKDTree, SklearnKNN


def test_knn_implementations_consistency():
    """Validates that all optimized kNN implementations return identical results.

    Compares the distances and indices generated by scipy and sklearn tree-based
    algorithms against the exact numpy brute-force implementation.
    """
    config = TrackSimulationConfig(
        hits_per_track=5,
        noise_ratio=0.1,
        sigma_pos=0.5,
        sigma_dir=0.05,
        vertex_spread=10.0,
        seed=42,
    )
    features, _ = generate_tracks(n_tracks=20, n_noise=10, config=config)
    k_neighbors = 5

    reference_model = NumpyBruteForce()
    reference_model.fit(features)
    reference_distances, reference_indices = reference_model.kneighbors(
        features, k=k_neighbors
    )

    implementations_to_test = [
        ScipyCKDTree(),
        SklearnKNN(algorithm="kd_tree"),
        SklearnKNN(algorithm="ball_tree"),
    ]

    for model in implementations_to_test:
        model.fit(features)
        test_distances, test_indices = model.kneighbors(features, k=k_neighbors)

        assert np.allclose(reference_distances, test_distances, rtol=1e-4, atol=1e-4)
        assert np.array_equal(reference_indices, test_indices)
